language: python

python:
  - "3.4"

env:
  - ES_VERSION=2.4.0

os: linux

cache:
  pip: true

jdk:
  - oraclejdk8

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .

script:
  - java -version
  - ./travis-run.sh

after_success:
  - coveralls
